// Global environment variables for all tests (unit + e2e)
// These mock values allow tests to run without real infrastructure.
process.env.NODE_ENV = 'test'
process.env.PORT = '3001'
process.env.DATABASE_URL = 'postgresql://test:test@localhost:5432/lintwise_test'
process.env.JWT_SECRET = 'test-jwt-secret-that-is-at-least-32-characters-long'
process.env.JWT_REFRESH_SECRET = 'test-refresh-secret-that-is-at-least-32-characters'
process.env.JWT_ACCESS_EXPIRY = '7d'
process.env.JWT_REFRESH_EXPIRY = '30d'
process.env.REDIS_URL = 'redis://localhost:6379'
process.env.GEMINI_API_KEY = 'test-gemini-api-key'
process.env.FRONTEND_URL = 'http://localhost:5173'
process.env.MAIL_HOST = 'smtp.test.com'
process.env.MAIL_PORT = '587'
process.env.MAIL_USER = 'test@lintwise.com'
process.env.MAIL_PASS = 'test-mail-password'
process.env.MAIL_FROM = 'LintWise Test <test@lintwise.com>'
